#include "shaderlib/cshader.h"
class sdk_debugluxel_ps30_Static_Index
{
public:
	sdk_debugluxel_ps30_Static_Index( )
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderStaticTest_sdk_debugluxel_ps30 0
class sdk_debugluxel_ps30_Dynamic_Index
{
public:
	sdk_debugluxel_ps30_Dynamic_Index()
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderDynamicTest_sdk_debugluxel_ps30 0
