name: Mapbase GCC/G++ (SP games.sln)

on:
  push:
  pull_request:
    branches:
      - develop
    paths:
      - .github/workflows/mapbase_sp-games-c-cpp.yml
      - sp/src/game/**
      - sp/src/mathlib/**
      - sp/src/responserules/runtime/**
      - sp/src/tier1/**
      - sp/src/vgui2/vgui_controls/**
      - sp/src/vscript/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install GCC/G++ multilib
      run: sudo apt-get install gcc-multilib g++-multilib

    - name: Create game projects
      working-directory: sp/src
      run: ./creategameprojects

    - name: Build
      working-directory: sp/src
      run: make -f games.mak
      
    - name: Publish Linux game SOs (HL2 Episodic)
      uses: actions/upload-artifact@v2
      with:
        name: Game SOs
        path: |
          sp/game/mod_episodic/bin/client.so
          sp/game/mod_episodic/bin/server.so
        if-no-files-found: error

    - name: Publish Linux game DBGs (HL2 Episodic)
      uses: actions/upload-artifact@v2
      with:
        name: Game DBGs
        path: |
          sp/game/mod_episodic/bin/client.so.dbg
          sp/game/mod_episodic/bin/server.so.dbg
        if-no-files-found: error
