name: Mapbase - Build Blank SP Projects

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/mapbase_build-sp-rel-games.yml'
      - '.github/workflows/mapbase_build-sp-rel-shaders.yml'
      - '.github/workflows/mapbase_build-sp-rel-maptools.yml'
      - 'sp/src/game/**'
      - 'sp/src/mathlib/**'
      - 'sp/src/responserules/runtime/**'
      - 'sp/src/tier1/**'
      - 'sp/src/vgui2/vgui_controls/**'
      - 'sp/src/vscript/**'
      - 'sp/src/materialsystem/**'
      - 'sp/src/utils/vbsp/**'
      - 'sp/src/utils/vvis/**'
      - 'sp/src/utils/vvis_launcher/**'
      - 'sp/src/utils/vrad/**'
      - 'sp/src/utils/vrad_launcher/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No matching build workflow" '
