name: Build Map Tool Projects #(SP Release)

on:
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/mapbase_build-sp-rel-maptools.yml'
      - 'sp/src/vpc_scripts/**'
      - 'sp/src/utils/vbsp/**'
      - 'sp/src/utils/vvis/**'
      - 'sp/src/utils/vvis_launcher/**'
      - 'sp/src/utils/vrad/**'
      - 'sp/src/utils/vrad_launcher/**'
      - 'sp/src/mathlib/**'
      - 'sp/src/tier1/**'
      - 'sp/src/vgui2/vgui_controls/**'
      - 'sp/src/vscript/**'

jobs:
  build_maptools:
    uses: ./.github/workflows/mapbase_build-base.yml
    with:
      configuration: 'Release'
      branch: 'sp'
      project-group: 'maptools'
      solution-name: 'maptools'
